# Generated by Django 3.1.1 on 2020-09-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uniqueindex',
            unique_together={('sequence', 'stock')},
        ),
        migrations.AlterIndexTogether(
            name='uniqueindex',
            index_together=set(),
        ),
    ]
