# Generated by Django 3.1 on 2020-09-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='uuid',
        ),
    ]
