# Generated by Django 3.1.1 on 2020-09-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test2',
            field=models.TextField(default='ABC', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='test3',
            field=models.TextField(default='ABC', max_length=500),
        ),
    ]
