# Generated by Django 3.1.1 on 2020-09-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='extensions',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='file_name_extensions',
            new_name='orginal_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_name_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='orginal_file_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='relative_path',
        ),
    ]
