# Generated by Django 3.1.2 on 2020-11-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0002_jsons'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSerializer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('props1', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'test_serializer',
            },
        ),
    ]
