# Generated by Django 3.1.1 on 2020-09-26 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0002_auto_20200927_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_test.file')),
            ],
            options={
                'db_table': 'file_details',
            },
        ),
    ]
