# Generated by Django 3.1.1 on 2020-10-01 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0003_auto_20200930_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='django_test.album'),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=set(),
        ),
    ]
