# Generated by Django 3.1.1 on 2020-09-26 19:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0003_filedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_url',
            field=models.FileField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filedetail',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='django_test.file'),
        ),
    ]
