# Generated by Django 3.1.1 on 2020-09-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_test', '0004_remove_child_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='child',
            field=models.ManyToManyField(related_name='child', to='django_test.Child'),
        ),
    ]
